version: '3.8'

services:
  semantic-worker:
    build: .
    container_name: py-semantic-worker
    env_file:
      - .env
    volumes:
      # Mount tmp dir for audio file downloads
      - semantic-tmp:/tmp/semantic-worker
    restart: unless-stopped
    command: python main.py

volumes:
  semantic-tmp:
